@startuml
'https://plantuml.com/class-diagram

class Bomb {
    - subscibers:List<Subscriber>
    + addSubsciber(Subsciber subsciber):void
    + bomb(int locationX, int locationY, int speedX, int speedY)
    + active(HeroAircraft heroaircraft):void
}
interface Subscriber
{
    update():void
}
abstract class AbstractAircraft
{
    # maxHp:int
    # hp:int
    # shootNum:int
    # power:int
    # direction:int
    - strategy:Strategy
    + AbstractAircraft(int locationX, int locationY, int speedX, int speedY, int hp)
    + decreaseHp(int decrease):void
    + getStrategy():Strategy
    + executeShoot(int x,int y,int speedX,int speedY,int shootNum,int power,int direction,boolean flag):List<BaseBullet>
    + update():void
    + update1():void
    + reset():void
 }
AbstractAircraft-right.>Subscriber
Subscriber<--o Bomb


@enduml